on:
  pull_request:
    branches:
      - 'develop'
    types:
      - closed

jobs:
  call-reusable:
    uses: akshaypgore/web-app/.github/workflows/develop-branch.yaml@master
    with:
      branch: ${GITHUB_REF_NAME}