name: Develop Branch - Build and Push

on:
  pull_request:
    branches:
      - 'develop'
    types:
      - closed

jobs:
  call-reusable:
    uses: akshaypgore/ci-cd-workflows/.github/workflows/reusable-build-push.yaml@master
    # secrets:
    #   REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
    #   REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
