name: Feature Branch - Build and Push

on:
  push:
    branches:
      - feature/**

jobs:
  build-and-push:
    uses: akshaypgore/ci-cd-workflows/.github/workflows/reusable-build-push.yml@master
    # secrets:
    #   REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
    #   REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

# jobs:
#   call-reusable:
#     permissions:
#       security-events: write # Required to view code scanning results
#       actions: read
#       contents: read         # Standard permission to checkout code
#     uses: akshaypgore/ci-cd-workflows/.github/workflows/feature-branch.yaml@master
#     secrets: inherit
#     with:
#       branch: ${{ github.ref_name }}
#       repo: ${{ github.event.repository.name }}
#       dockerhub_repo: "akshaygore"